### ISSUE TITLE
CI for QUIC stuff

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#3551] opened 2018-05-01 06:11 UTC
We don't have any environment for CI builds that can run unit tests for QUIC stuff.
The environment requires ~Open SSL 1.1.1.~ a special OpenSSL made by tatsuhiro-t.

**Comment by maskit** [comment] 2019-06-24 05:38
Update: The latest official OpenSSL is not enough. Our QUIC impl. requires the special version made by tatsuhiro-t.

**Comment by maskit** [comment] 2019-07-12 06:47
@zwoop I really think we need a CI box that can run tests for QUIC. Otherwise it will follow the same path as BoringSSL support. Ideally, we should have it before merging QUIC branch for 9.0 so that nobody can break QUIC support.

For "quic-20" branch, which will be merged for 9.0, uses "quic-draft-20" branch on https://github.com/tatsuhiro-t/openssl

**Comment by bneradt** [comment] 2021-06-22 15:04
We are in the process of transitioning to a new CI environment. As a part of that process, we have configured the Centos CI job, which runs `make check` and the regression tests, to build against the openssl-quic library. For our current centos:8 new CI docker image, that version of openssl quic is:

repository: https://github.com/quictls/openssl.git
branch: OpenSSL_1_1_1k+quic

This is the branch that the quic version of curl presently builds against and what ATS currently supports.

Here is a link to that new CI job:
https://jenkins.trafficserver.org/view/Github/job/Github_Builds/job/centos/

In addition, the AuTest CI jobs will also test ATS built against this same version of openssl-quic. That is already done with the present CI as well.

Thus all the work for this issue is effectively done. However, I'll leave this ticket open until we finish migrating to the new CI system and this job is being run against new PRs.

**Comment by bneradt** [comment] 2021-06-22 15:28
I did an experiment with the new CI job to verify it functions like we expect it to. A week ago I made the following PR to fix the catch tests when compiled against openssl-quic: https://github.com/apache/trafficserver/pull/7944

I did the following run against master, which has the fix from that PR:
https://jenkins.trafficserver.org/view/Github/job/Github_Builds/job/centos/37/

The test passed, as expected.

I then did the following run on the commit before that PR got merged in:
https://jenkins.trafficserver.org/view/Github/job/Github_Builds/job/centos/38/

That job failed, as expected since there was a compilation issue with the openssl QUIC unit tests:

```
In file included from ./test/test_QUICFlowController.cc:27:
../quic/Mock.h:198:3: error: 'int MockQUICConnectionInfoProvider::select_next_protocol(SSL*, const unsigned char**, unsigned char*, const unsigned char*, unsigned int) const' marked 'override', but does not override
   select_next_protocol(SSL *ssl, const unsigned char **out, unsigned char *outlen, const unsigned char *in,
   ^~~~~~~~~~~~~~~~~~~~
../quic/Mock.h:516:3: error: 'int MockQUICConnection::select_next_protocol(SSL*, const unsigned char**, unsigned char*, const unsigned char*, unsigned int) const' marked 'override', but does not override
   select_next_protocol(SSL *ssl, const unsigned char **out, unsigned char *outlen, const unsigned char *in,
   ^~~~~~~~~~~~~~~~~~~~
```

This demonstrates that the new CI job is compiling the unit and regression tests against openssl-quic as we desire and is capable of finding issues with openssl-quic builds.

Again, as mentioned in the previous comment, I'll leave this issue open until we transition to the new CI system and new PRs are run against this job.

**Comment by maskit** [comment] 2021-06-23 00:27
Thank you for setting up the CI environment.

> In addition, the AuTest CI jobs will also test ATS built against this same version of openssl-quic. That is already done with the present CI as well.

Does this mean we can run autest test cases that requires curl that supports HTTP/3? 
https://github.com/apache/trafficserver/blob/9e7cece7641b282a76fb95798f29e4cd39b51bc8/tests/gold_tests/timeout/active_timeout.test.py#L67-L70

**Comment by bneradt** [comment] 2021-06-23 22:23
Wow, I'm glad you asked this.

The answer is yes, we can run those tests. And indeed when I run it locally with our new CI's centos:8 docker image I run that test:

```
$ ./autest.sh --sandbox /tmp/sb/ --clean=none --ats-bin ~/build/ts_asf_master_test_quic_build/bin/ -f active_timeout
Python 3.6 or newer detected!
python3-dev/devel detected!
pipenv detected!
Using the pre-existing virtual environment.
Environment config finished. Running AuTest...
Running Test active_timeout:.... Passed
```

It's subtle, but notice the four dots. That fourth dot corresponds to the HTTP/3 test you describe.

I had done work to make that happen, and I thought it would carry over to the new jenkins server. But since you asked, I went to grab it's output to prove in this issue that it was running with the QUIC version of curl but noticed it had only three dots with the latest invocation. Working with @ezelkow1 , we got the PATH environment updated in the jenkins shell so that it builds with and runs the AuTests with the openssl-quic version of curl. Here's the latest run, with that now working:

https://jenkins.trafficserver.org/view/Github/job/Github_Builds/job/autest/72/console

```
Running Test active_timeout:.... Passed
```

Again, notice the four dots, indicating that the HTTP/3 test was run.

Thanks again for the thoughtful question.

**Comment by maskit** [comment] 2021-06-24 00:17
Awesome, thank you.

**Comment by bneradt** [comment] 2022-01-21 17:37
Closing this since we are now using the new CI which is running with HTTP/3. And the latest autest jenkins run still shows the HTTP/3 test running:

https://ci.trafficserver.apache.org/view/Github/job/Github_Builds/job/autest/511/console

```
Running Test active_timeout:.... Passed
```

**Closed by bneradt** 2022-01-21 17:37 UTC
Labels: Tests, QUIC, CI
