### ISSUE TITLE
Ignore frames that it receives on closed streams after it has sent a RST_STREAM frame

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#6273] opened 2019-12-18 23:36 UTC
It looks like ATS violate 5.1.  Stream States - closed https://tools.ietf.org/html/rfc7540#page-20

> If this state is reached as a result of sending a RST_STREAM
frame, the peer that receives the RST_STREAM might have already
sent -- or enqueued for sending -- frames on the stream that
cannot be withdrawn.  An endpoint MUST ignore frames that it
receives on closed streams after it has sent a RST_STREAM frame.
An endpoint MAY choose to limit the period over which it ignores
frames and treat frames that arrive after this time as being in
error.

**Comment by maskit** [comment] 2020-10-21 04:48
Duplicate of #5675

**Closed by maskit** 2020-10-21 04:48 UTC
Labels: HTTP/2
