### ISSUE TITLE
Delete proxy/AbstractBuffer.{cc,h}

### ISSUE THREAD

**Issue by danobi** [apache/trafficserver#1622] opened 2017-03-30 22:19 UTC
These files are never used, despite the fact that other comments seem to indicate otherwise.

Just another day in the logging subsystem, I guess.

**Comment by zwoop** [comment] 2017-03-31 05:26
Dupe of #1623. Please don't file a PR and Issue at the same time. You only need an issue if you don't have code.

**Closed by zwoop** 2017-03-31 05:26 UTC
Labels: Cleanup

**Comment by danobi** [comment] 2017-03-31 14:53
Sorry. I made this issue to put off the task but I never ended up putting it off.
