### ISSUE TITLE
microDNS crash causes failures in redirect_actions autest

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#5793] opened 2019-08-07 23:08 UTC
Redirect_actions fails with fairly high frequency.  Different cases will fail.  The immediate cause is a gold file mismatch due to an unexpected HTTP response.  Finally tracked  it down in an autest failure on my PR this evening that the micro DNS crashed after responding to the last successful test case.  Then subsequent DNS requests fail, and ATS cannot perform the appropriate redirect action for the type of address.

DNS stream.all.out for this evening's failing case.
```
Domain name: iwillredirect.test.
[127.0.0.1]
Domain name: testdomain10_0_0_1.test.
[10.0.0.1]
Domain name: testdomain_fc00__1_.test.
[fc00::1]
Domain name: testdomain127_1_2_3.test.
[127.1.2.3]
Domain name: testdomain224_1_2_3.test.
[224.1.2.3]
Domain name: testdomain_ff42___.test.
[ff42::]
Domain name: testdomain169_254_0_1.test.
[169.254.0.1]
Domain name: testdomain_fe80___.test.
[fe80::]
Domain name: testdomain72_30_35_10.test.
[72.30.35.10]
Domain name: testdomain_2001_4998_58_1836__10_.test.
[2001:4998:58:1836::10]
Domain name: testdomain10_217_6_28.test.
[10.217.6.28]
Domain name: testdomain64_202_188_14.test.
[64.202.188.14]
Starting DNS on address 127.0.0.1 port 61696...


UDP request 2019-08-07 22:21:49.411352 (127.0.0.1 44708):
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65077
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;iwillredirect.test.            IN      A
---- Reply: ----
 ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65077
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;iwillredirect.test.            IN      A
;; ANSWER SECTION:
iwillredirect.test.     300     IN      A       127.0.0.1


UDP request 2019-08-07 22:21:49.436376 (127.0.0.1 44708):
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55033
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain10_0_0_1.test.       IN      A
---- Reply: ----
 ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55033
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain10_0_0_1.test.       IN      A
;; ANSWER SECTION:
testdomain10_0_0_1.test. 300     IN      A       10.0.0.1


UDP request 2019-08-07 22:21:49.576167 (127.0.0.1 44708):
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24737
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain_fc00__1_.test.      IN      A
---- Reply: ----
 ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 24737
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain_fc00__1_.test.      IN      A


UDP request 2019-08-07 22:21:49.596277 (127.0.0.1 44708):
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6597
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain_fc00__1_.test.      IN      AAAA
---- Reply: ----
 ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6597
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain_fc00__1_.test.      IN      AAAA
;; ANSWER SECTION:
testdomain_fc00__1_.test. 300     IN      AAAA    fc00::1


UDP request 2019-08-07 22:21:49.688272 (127.0.0.1 44708):
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33872
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain127_1_2_3.test.      IN      A
---- Reply: ----
 ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33872
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain127_1_2_3.test.      IN      A
;; ANSWER SECTION:
testdomain127_1_2_3.test. 300     IN      A       127.1.2.3


UDP request 2019-08-07 22:21:49.828581 (127.0.0.1 44708):
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43881
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain224_1_2_3.test.      IN      A
---- Reply: ----
 ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43881
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain224_1_2_3.test.      IN      A
;; ANSWER SECTION:
testdomain224_1_2_3.test. 300     IN      A       224.1.2.3


UDP request 2019-08-07 22:21:49.917403 (127.0.0.1 44708):
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43035
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain_ff42___.test.       IN      A
---- Reply: ----
 ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 43035
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain_ff42___.test.       IN      A


UDP request 2019-08-07 22:21:49.938068 (127.0.0.1 44708):
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12032
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain_ff42___.test.       IN      AAAA
---- Reply: ----
 ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12032
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain_ff42___.test.       IN      AAAA
;; ANSWER SECTION:
testdomain_ff42___.test. 300     IN      AAAA    ff42::


UDP request 2019-08-07 22:21:50.039013 (127.0.0.1 44708):
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60928
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain169_254_0_1.test.    IN      A
---- Reply: ----
 ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60928
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain169_254_0_1.test.    IN      A
;; ANSWER SECTION:
testdomain169_254_0_1.test. 300     IN      A       169.254.0.1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dnslib/dns.py", line 678, in parse
    qname = buffer.decode_name()
  File "/usr/local/lib/python3.6/site-packages/dnslib/label.py", line 255, in decode_name
    l = self.get(length)
  File "/usr/local/lib/python3.6/site-packages/dnslib/buffer.py", line 64, in get
    (self.offset,self.remaining(),length))
dnslib.buffer.BufferError: Not enough bytes [offset=13,remaining=27,requested=116]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/microdns/microdns.py", line 59, in handle
    self.send_data(self.dns_response(data))
  File "/usr/local/lib/python3.6/site-packages/microdns/microdns.py", line 70, in dns_response
    request = DNSRecord.parse(data)
  File "/usr/local/lib/python3.6/site-packages/dnslib/dns.py", line 106, in parse
    questions.append(DNSQuestion.parse(buffer))
  File "/usr/local/lib/python3.6/site-packages/dnslib/dns.py", line 683, in parse
    buffer.offset,e))
dnslib.dns.DNSError: Error unpacking DNSQuestion [offset=13]: Not enough bytes [offset=13,remaining=27,requested=116]


UDP request 2019-08-07 22:21:50.169075 (127.0.0.1 44708):
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dnslib/dns.py", line 678, in parse
    qname = buffer.decode_name()
  File "/usr/local/lib/python3.6/site-packages/dnslib/label.py", line 255, in decode_name
    l = self.get(length)
  File "/usr/local/lib/python3.6/site-packages/dnslib/buffer.py", line 64, in get
    (self.offset,self.remaining(),length))
dnslib.buffer.BufferError: Not enough bytes [offset=13,remaining=27,requested=116]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/microdns/microdns.py", line 59, in handle
    self.send_data(self.dns_response(data))
  File "/usr/local/lib/python3.6/site-packages/microdns/microdns.py", line 70, in dns_response
    request = DNSRecord.parse(data)
  File "/usr/local/lib/python3.6/site-packages/dnslib/dns.py", line 106, in parse
    questions.append(DNSQuestion.parse(buffer))
  File "/usr/local/lib/python3.6/site-packages/dnslib/dns.py", line 683, in parse
    buffer.offset,e))
dnslib.dns.DNSError: Error unpacking DNSQuestion [offset=13]: Not enough bytes [offset=13,remaining=27,requested=116]


UDP request 2019-08-07 22:22:10.166592 (127.0.0.1 44708):

=== ^C received, shutting down microDNS ===
```

**Comment by oknet** [comment] 2019-08-24 07:39
meet the same issue:

```
DP request 2019-08-24 05:19:22.949566 (127.0.0.1 24187):
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26397
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain72_30_35_10.test.    IN      A
---- Reply: ----
 ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26397
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain72_30_35_10.test.    IN      A
;; ANSWER SECTION:
testdomain72_30_35_10.test. 300     IN      A       72.30.35.10
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dnslib/dns.py", line 678, in parse
    qname = buffer.decode_name()
  File "/usr/local/lib/python3.6/site-packages/dnslib/label.py", line 255, in decode_name
    l = self.get(length)
  File "/usr/local/lib/python3.6/site-packages/dnslib/buffer.py", line 64, in get
    (self.offset,self.remaining(),length))
dnslib.buffer.BufferError: Not enough bytes [offset=13,remaining=42,requested=116]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/microdns/microdns.py", line 59, in handle
    self.send_data(self.dns_response(data))
  File "/usr/local/lib/python3.6/site-packages/microdns/microdns.py", line 70, in dns_response
    request = DNSRecord.parse(data)
  File "/usr/local/lib/python3.6/site-packages/dnslib/dns.py", line 106, in parse
    questions.append(DNSQuestion.parse(buffer))
  File "/usr/local/lib/python3.6/site-packages/dnslib/dns.py", line 683, in parse
    buffer.offset,e))
dnslib.dns.DNSError: Error unpacking DNSQuestion [offset=13]: Not enough bytes [offset=13,remaining=42,requested=116]
```

**Comment by oknet** [comment] 2019-08-24 09:57
I made a dns request for testdomain72_30_35_10.test:

```
        0x0000:  4500 0053 c600 0000 4011 0000 ac16 022c  E..S....@......,
        0x0010:  ac15 15fe ce5f 0035 003f 70a6 6820 0120  ....._.5.?p.h...
        0x0020:  0001 0000 0000 0001 1574 6573 7464 6f6d  .........testdom
        0x0030:  6169 6e37 325f 3330 5f33 355f 3130 0474  ain72_30_35_10.t
        0x0040:  6573 7400 0001 0001 0000 2910 0000 0000  est.......).....
        0x0050:  0000 00 
```

The udp payload start from offset 0x1c: 6820 0120 ... , decoding the packet manually:

Header: 12 bytes
```
        0x0010:                                6820 0120  ............h...
        0x0020:  0001 0000 0000 0001                      ................
```

Name Part 1: 1 + 21 bytes
```
        0x0020:                      1574 6573 7464 6f6d  .........testdom
        0x0030:  6169 6e37 325f 3330 5f33 355f 3130       ain72_30_35_10..
```
Name Part 2: 1 + 4 bytes
```
        0x0030:                                           ...............t
        0x0040:  6573 74                                  est.............
```
Name Part 3: 1 bytes (0 length)
```
        0x0040:         00                                ................
```
Query Type(A=0001) and Class(IN=0001): 4 bytes
```
        0x0040:            0001 0001                      ................
```
Rest bytes: 11 bytes
```
        0x0040:                      0000 2910 0000 0000  ................
        0x0050:  0000 00 
```

According to the dnslib error message:

```
dnslib.buffer.BufferError: Not enough bytes [offset=13,remaining=42,requested=116]
```

offset=13: 0x15, the 1st byte of name part1.
remaining=42: sizeof(Name Part1) - 1 byte(offset 13) + sizeof(Name Part2) + sizeof(Name Part3) + sizeof(Query Type and Class) + sizeof (Rest bytes) = 21 + 5 + 1+ 4 + 11 = 42
requested=116: 116 == 0x74, it is the 2nd bytes of name part1.

The DNS request which received by `microdns` missing 1 byte.

- dnslib bug ?
- ATS bug ?

Where did it lose 1 byte?

**Comment by scw00** [comment] 2019-08-24 11:07
It seems the public server can correctly resolve this dns request .

![image](https://user-images.githubusercontent.com/12470347/63636467-4ff57a00-c6a2-11e9-8141-31cef1c42276.png)

**Comment by YuanYingdong** [comment] 2019-08-24 12:39
> Header: 12 bytes
> 
> ```
>         0x0010:                                6820 0120  ............h...
>         0x0020:  0001 0000 0000 0001                      ................
> ```
> 

> Rest bytes: 11 bytes
> 
> ```
>         0x0040:                      0000 2910 0000 0000  ................
>         0x0050:  0000 00 
> ```

I'm confused about the Additional Record in the query , and the data seems to be incorrect.

**Comment by scw00** [comment] 2019-08-26 01:09
This is what I got from autest ci box.

```
[Aug 25 17:22:07.358] [ET_NET 0] DEBUG: <DNS.cc:1150 (write_dns_event)> (dns) send dns request: 0x70 0xfa 0x1 0x0 0x0 0x1 0x0 0x0 0x0 0x0 0x0 0x0 0x15 0x74 0x65 0x73 0x74 0x64 0x6f 0x6d 0x61 0x69 0x6e 0x31 0x36 0x39 0x5f 0x32 0x35 0x34 0x5f 0x30 0x5f 0x31 0x4 0x74 0x65 0x73 0x74 0x0 0x0 0x1 0x0 0x
```

And please do 
```
echo 70fa010000010000000000001574657374646f6d61696e3136395f3235345f305f3104746573740000010001 | xxd -r -ps > dns_request
```

And `nc` this against public dns. 
```
nc -u 211.138.180.3 53 < dns_request
```

**Comment by oknet** [comment] 2019-08-26 04:32
Thanks to @scw00 for reproducing the problems in the CI system.

By analyzing the MicroDNS log and ATS log with these below commands:

for microdns log:
```
wget -q --no-check-certificate -O - https://ci.trafficserver.apache.org/autest/ausb-5875.10893/redirect_actions/_output/redirect_actions-dns/stream.all.txt | grep "^;.*id:" -A3 | grep -E "(id:|IN)" | sed -e 's/^;//' | awk '{if($(NF-1) == "id:") saveid=$NF; else print "id =", saveid, $1}' > dnsserver.log
```

for ats log:
``` 
wget -q --no-check-certificate -O - https://ci.trafficserver.apache.org/autest/ausb-5875.10893/redirect_actions/_output/redirect_actions-ts_default_reject_linklocal_return_loopback_follow_multicast_reject_private_reject_routable_reject_self_return/stream.all.txt | sed -e 's/,//g' | grep "id = "  | awk '{print "id =", $(NF-3), $(NF-6)"."}' > dnsclient.log 
``` 

There is 53 lines in dnsserver.log which means 53 dns requests was received by microdns.
And there is 19 lines in dnsclient.log which means 19 dns request was sent by ats.

I found repeat dns request from these 53 dns requests:

Part 1:
```
01 id = 46468 iwillredirect.test.
02 id = 16707 testdomain10_0_0_1.test.
03 id = 42667 testdomain_fc00__1_.test.
04 id = 58228 testdomain_fc00__1_.test.
05 id = 58989 testdomain127_1_2_3.test.
06 id = 10642 testdomain224_1_2_3.test.
07 id = 34798 testdomain_ff42___.test.
08 id = 34906 testdomain_ff42___.test.
09 id = 28922 testdomain169_254_0_1.test.
10 id = 60165 testdomain_fe80___.test.
11 id = 29691 testdomain_fe80___.test.
12 id = 43192 testdomain72_30_35_10.test.
13 id = 41910 testdomain_2001_4998_58_1836__10_.test.
14 id = 18028 testdomain_2001_4998_58_1836__10_.test.
15 id = 51434 testdomain172_17_0_1.test.
16 id = 48904 testdomain64_202_187_113.test.
17 id = 23400 testdomain10_217_5_33.test.
18 id =  4618 testdomainNone.test.
19 id = 11233 testdomainNone.test.
```

Part 2:
```
20 id = 53491 iwillredirect.test.
21 id = 56891 testdomain10_0_0_1.test.
22 id =  4194 testdomain_fc00__1_.test.
23 id =  9771 testdomain_fc00__1_.test.
24 id = 20761 testdomain127_1_2_3.test.
25 id = 48530 testdomain224_1_2_3.test.
26 id = 18372 testdomain_ff42___.test.
27 id = 51989 testdomain_ff42___.test.
28 id = 33722 testdomain169_254_0_1.test.
29 id = 15441 testdomain_fe80___.test.
30 id = 28586 testdomain_fe80___.test.
31 id = 48449 testdomain72_30_35_10.test.
32 id = 36125 testdomain_2001_4998_58_1836__10_.test.
33 id =  6986 testdomain_2001_4998_58_1836__10_.test.
34 id = 11066 testdomain172_17_0_1.test.
35 id = 32840 testdomain64_202_187_113.test.
36 id = 63171 testdomain10_217_5_33.test.
37 id = 25248 testdomainNone.test.
38 id = 29217 testdomainNone.test.
```

Part 3:
```
39 id = 30429 iwillredirect.test.
40 id = 48202 testdomain10_0_0_1.test.
41 id = 53080 testdomain_fc00__1_.test.
42 id = 48651 testdomain_fc00__1_.test.
43 id = 57029 testdomain127_1_2_3.test.
44 id = 43603 testdomain224_1_2_3.test.
45 id = 43353 testdomain_ff42___.test.
46 id = 19043 testdomain_ff42___.test.
47 id = 25771 testdomain169_254_0_1.test.
48 id =  3882 testdomain_fe80___.test.
49 id = 15731 testdomain_fe80___.test.
50 id = 39148 testdomain72_30_35_10.test.
51 id =  2104 testdomain_2001_4998_58_1836__10_.test.
52 id = 50619 testdomain_2001_4998_58_1836__10_.test.
53 id = 27242 testdomain172_17_0_1.test.
```

The Part 1 and the Part 2 have the same 19 dns requests, while the Part 3 has only 16 dns requests because the microserver server is closed by autest (the last 2 lines show that the 17th request has arrived).

I noticed the Part 1 is identical to dnsclient.log include the dns request id.

Requests with IDs of 25771 and 27242 caused the MicroDNS to crash. But I can not find these 2 IDs in the ATS log.

```
UDP request 2019-08-26 00:22:13.747496 (127.0.0.1 22037):
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25771
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain169_254_0_1.test.    IN      A
---- Reply: ----
 ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25771
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain169_254_0_1.test.    IN      A
;; ANSWER SECTION:
testdomain169_254_0_1.test. 300     IN      A       169.254.0.1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dnslib/dns.py", line 678, in parse
    qname = buffer.decode_name()
  File "/usr/local/lib/python3.6/site-packages/dnslib/label.py", line 255, in decode_name
    l = self.get(length)
  File "/usr/local/lib/python3.6/site-packages/dnslib/buffer.py", line 64, in get
    (self.offset,self.remaining(),length))
dnslib.buffer.BufferError: Not enough bytes [offset=13,remaining=33,requested=116]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/microdns/microdns.py", line 59, in handle
    self.send_data(self.dns_response(data))
  File "/usr/local/lib/python3.6/site-packages/microdns/microdns.py", line 70, in dns_response
    request = DNSRecord.parse(data)
  File "/usr/local/lib/python3.6/site-packages/dnslib/dns.py", line 106, in parse
    questions.append(DNSQuestion.parse(buffer))
  File "/usr/local/lib/python3.6/site-packages/dnslib/dns.py", line 683, in parse
    buffer.offset,e))
dnslib.dns.DNSError: Error unpacking DNSQuestion [offset=13]: Not enough bytes [offset=13,remaining=33,requested=116]
```

```
UDP request 2019-08-26 00:22:14.632157 (127.0.0.1 22037):
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27242
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain172_17_0_1.test.     IN      A
---- Reply: ----
 ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27242
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;testdomain172_17_0_1.test.     IN      A
;; ANSWER SECTION:
testdomain172_17_0_1.test. 300     IN      A       172.17.0.1


UDP request 2019-08-26 00:22:14.844520 (127.0.0.1 22037):
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dnslib/dns.py", line 678, in parse
    qname = buffer.decode_name()
  File "/usr/local/lib/python3.6/site-packages/dnslib/label.py", line 255, in decode_name
    l = self.get(length)
  File "/usr/local/lib/python3.6/site-packages/dnslib/buffer.py", line 64, in get
    (self.offset,self.remaining(),length))
dnslib.buffer.BufferError: Not enough bytes [offset=13,remaining=33,requested=116]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/microdns/microdns.py", line 59, in handle
    self.send_data(self.dns_response(data))
  File "/usr/local/lib/python3.6/site-packages/microdns/microdns.py", line 70, in dns_response
    request = DNSRecord.parse(data)
  File "/usr/local/lib/python3.6/site-packages/dnslib/dns.py", line 106, in parse
    questions.append(DNSQuestion.parse(buffer))
  File "/usr/local/lib/python3.6/site-packages/dnslib/dns.py", line 683, in parse
    buffer.offset,e))
dnslib.dns.DNSError: Error unpacking DNSQuestion [offset=13]: Not enough bytes [offset=13,remaining=33,requested=116]
```

Why is it getting nearly 3 times the dns request in `MicroDNS` ?

**Comment by scw00** [comment] 2019-08-26 07:26
This is 25771

```
[Aug 25 17:22:13.746] [ET_NET 0] DEBUG: <DNS.cc:1150 (write_dns_event)> (dns) send dns request: 0x64 0xab 0x1 0x0 0x0 0x1 0x0 0x0 0x0 0x0 0x0 0x0 0x15 0x74 0x65 0x73 0x74 0x64 0x6f 0x6d 0x61 0x69 0x6e 0x31 0x36 0x39 0x5f 0x32 0x35 0x34 0x5f 0x30 0x5f 0x31 0x4 0x74 0x65 0x73 0x74 0x0 0x0 0x1 0x0 0x1 
[Aug 25 17:22:13.747] [ET_NET 0] DEBUG: <DNS.cc:1184 (write_dns_event)> (dns) sent qname = testdomain169_254_0_1.test, id = 25771, nameserver = 0
```

**Comment by oknet** [comment] 2019-08-26 07:40
Got it, so we have 3 ATS instance and 1 MicroDNS instance.

There are 3 parts of ATS dns requests (from ats log):

Part 1:
```
id = 46468 iwillredirect.test.
id = 16707 testdomain10_0_0_1.test.
id = 42667 testdomain_fc00__1_.test.
id = 58228 testdomain_fc00__1_.test.
id = 58989 testdomain127_1_2_3.test.
id = 10642 testdomain224_1_2_3.test.
id = 34798 testdomain_ff42___.test.
id = 34906 testdomain_ff42___.test.
id = 28922 testdomain169_254_0_1.test.
id = 60165 testdomain_fe80___.test.
id = 29691 testdomain_fe80___.test.
id = 43192 testdomain72_30_35_10.test.
id = 41910 testdomain_2001_4998_58_1836__10_.test.
id = 18028 testdomain_2001_4998_58_1836__10_.test.
id = 51434 testdomain172_17_0_1.test.
id = 48904 testdomain64_202_187_113.test.
id = 23400 testdomain10_217_5_33.test.
id = 4618 testdomainNone.test.
id = 11233 testdomainNone.test.
```

Part 2:
```
# wget -q --no-check-certificate -O - https://ci.trafficserver.apache.org/autest/ausb-5875.10893/redirect_actions/_output/redirect_actions-ts_default_return_linklocal_reject_loopback_follow_multicast_return_private_return_routable_return_self_reject/stream.all.txt | sed -e 's/,//g' | grep "id = "  | awk '{print "id =", $(NF-3), $(NF-6)"."}' 
id = 53491 iwillredirect.test.
id = 56891 testdomain10_0_0_1.test.
id = 4194 testdomain_fc00__1_.test.
id = 9771 testdomain_fc00__1_.test.
id = 20761 testdomain127_1_2_3.test.
id = 48530 testdomain224_1_2_3.test.
id = 18372 testdomain_ff42___.test.
id = 51989 testdomain_ff42___.test.
id = 33722 testdomain169_254_0_1.test.
id = 15441 testdomain_fe80___.test.
id = 28586 testdomain_fe80___.test.
id = 48449 testdomain72_30_35_10.test.
id = 36125 testdomain_2001_4998_58_1836__10_.test.
id = 6986 testdomain_2001_4998_58_1836__10_.test.
id = 11066 testdomain172_17_0_1.test.
id = 32840 testdomain64_202_187_113.test.
id = 63171 testdomain10_217_5_33.test.
id = 25248 testdomainNone.test.
id = 29217 testdomainNone.test.
```

Part 3:
```
# wget -q --no-check-certificate -O - https://ci.trafficserver.apache.org/autest/ausb-5875.10893/redirect_actions/_output/redirect_actions-ts_default_reject_loopback_return/stream.all.txt | sed -e 's/,//g' | grep "id = "  | awk '{print "id =", $(NF-3), $(NF-6)"."}' 
id = 30429 iwillredirect.test.
id = 48202 testdomain10_0_0_1.test.
id = 53080 testdomain_fc00__1_.test.
id = 48651 testdomain_fc00__1_.test.
id = 57029 testdomain127_1_2_3.test.
id = 43603 testdomain224_1_2_3.test.
id = 43353 testdomain_ff42___.test.
id = 19043 testdomain_ff42___.test.
id = 25771 testdomain169_254_0_1.test.      ==> failed
id = 3882 testdomain_fe80___.test.
id = 15731 testdomain_fe80___.test.
id = 39148 testdomain72_30_35_10.test.
id = 2104 testdomain_2001_4998_58_1836__10_.test.
id = 50619 testdomain_2001_4998_58_1836__10_.test.
id = 27242 testdomain172_17_0_1.test.      ==> failed
id = 2481 testdomain64_202_187_113.test.      ==> timeout
id = 2354 testdomain64_202_187_113.test.      ==> timeout
```

**Comment by oknet** [comment] 2019-08-26 10:21
@bcall @zwoop @scw00 There is a bug in autestsuite/microdns module.

https://bitbucket.org/autestsuite/microdns/src/master/src/microdns/microdns.py#lines-120,136

![image](https://user-images.githubusercontent.com/5242289/63683387-cfaf5000-c82c-11e9-9214-c1f317e64297.png)

It is a ctrl+c/ctrl+v code from https://docs.python.org/2/library/socketserver.html. 
The `strip()` should be removed here.

@scw00 try to reproduce the CI issue by PR #5875 , the below logs from: https://ci.trafficserver.apache.org/autest/ausb-5875.10893/redirect_actions/_output/redirect_actions-ts_default_reject_loopback_return/stream.all.txt

```
[Aug 25 17:22:14.844] [ET_NET 0] DEBUG: <DNS.cc:1143 (write_dns_event)> (dns) send query (qtype=1) for testdomain64_202_187_113.test to fd 22
[Aug 25 17:22:14.844] [ET_NET 0] DEBUG: <DNS.cc:1150 (write_dns_event)> (dns) send dns request: 0x9 0xb1 0x1 0x0 0x0 0x1 0x0 0x0 0x0 0x0 0x0 0x0 0x18 0x74 0x65 0x73 0x74 0x64 0x6f 0x6d 0x61 0x69 0x6e 0x36 0x34 0x5f 0x32 0x30 0x32 0x5f 0x31 0x38 0x37 0x5f 0x31 0x31 0x33 0x4 0x74 0x65 0x73 0x74 0x0 0x0 0x1 0x0 0x1 
[Aug 25 17:22:14.844] [ET_NET 0] DEBUG: <DNS.cc:1184 (write_dns_event)> (dns) sent qname = testdomain64_202_187_113.test, id = 2481, nameserver = 0
[Aug 25 17:22:14.844] [ET_NET 0] DEBUG: <P_DNSProcessor.h:224 (sent_one)> (dns) sent_one: failover_number for resolver 0 is 1
[Aug 25 17:22:34.841] [ET_NET 0] DEBUG: <DNS.cc:1245 (mainEvent)> (dns) timeout for query testdomain64_202_187_113.test
```

The DNS request ID = 2481(0x9 0xb1) and the first byte `0x09` is `\t`. The default behavior of `strip()` is to remove any `\t`, `\ r` and `\ n` from the beginning and end of the string. The first byte (0x09) has been removed from the DNS request and then report an error while parseing it by dnslib API.

**Comment by bryancall** [comment] 2021-08-30 23:33
Looks like this has been fixed.  Please reopen if there is still an issue.

**Closed by bryancall** 2021-08-30 23:33 UTC
Labels: Tests
