### ISSUE TITLE
Websockets are broken

### ISSUE THREAD

**Issue by Tchinmai7** [apache/trafficserver#2650] opened 2017-10-11 07:32 UTC
**Steps:**
1. Setup ATS 7.1.1 as a forward proxy
2. Point browser proxy to ATS
3. Visit http://agar.io/

**Request:**
`GET http://live-arena-cy3bhe.agar.io/`
`Host: live-arena-cy3bhe.agar.io`
`User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 Firefox/57.0`
`Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`
`Accept-Language: en-US,en;q=0.5`
`Accept-Encoding: gzip, deflate`
`Sec-WebSocket-Version: 13`
`Origin: http://agar.io`
`Sec-WebSocket-Extensions: permessage-deflate`
`Sec-WebSocket-Key: O14i+WkqqQNs2mRjBEOfmg==`
`Cookie: __cfduid=de3d6fff9ad2a5c9d999e2665a18f2f181504616106;`
`_ga=GA1.2.1992702657.1505217383; G_ENABLED_IDPS=google;`
`__gads=ID=d962cbf567c811cc:T=1505217390:S=ALNI_Ma__mLzPFCBnk_BnjT3IE376ULisg;` `_gid=GA1.2.182917083.1507706548; _gat=1`
`Connection: keep-alive, Upgrade`
`Pragma: no-cache`
`Cache-Control: no-cache`
`Upgrade: websocket`

**Response: **
`403 Tunnel Forbidden`

**ATS Logs **
**error.log**
20171011.07h20m28s RESPONSE: sent 172.19.153.27 status 403 (Tunnel Forbidden) for 'live-arena-cy3bhe.agar.io:80/'

**Comment by Tchinmai7** [comment] 2017-10-11 07:38
The https://html5demos.com/web-socket/ site seems to work without issues, as it makes a https: connection to https://remy-ws.glitch.me/ , and the server responds with an upgrade.
**Request**
`Host: remy-ws.glitch.me
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 Firefox/57.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: https://html5demos.com
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: Gq0S1bKhPORaYOR5xuOxYw==
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket`

**Response**
`Date: Wed, 11 Oct 2017 07:35:26 GMT
Connection: upgrade
upgrade: websocket
sec-websocket-accept: Zebfy1SbBKmtJARaRFAZpw0pwqo=`

**Comment by bryancall** [comment] 2019-05-22 20:49
@zizhong Can you take a look at this?  Are you still using web sockets?

**Comment by zizhong** [comment] 2019-05-22 21:08
@bryancall sure, will do.
I didn't hear any complaint about WebSocket, but we are on ats 6.2.x.
Haven't look closely into this module. I'll need some time to dig into it.

**Comment by zizhong** [comment] 2019-05-24 23:01
@Tchinmai7 what is the remap config you used to reproduce this issue?

**Comment by Tchinmai7** [comment] 2019-05-25 15:44
We used to use ATS in transparent proxy mode, and hence the remap.config was left untouched. 

Note: This issue was raised more than a year ago, and I haven't got a chance to work on this after that (I switched orgs)

**Comment by zizhong** [comment] 2019-06-27 05:28
Closing this for now since the user is not actively working on it anymore. Please feel free to reopen it is still an issue.

**Closed by zizhong** 2019-06-27 05:28 UTC
Labels: Websockets
