### ISSUE TITLE
Bad keyword messages should be nicer for sni.yaml

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#5957] opened 2019-09-24 19:33 UTC
While testing ATS 9.x, I had problems getting my sni.yaml file accepted.  A number of the errors gave line numbers and those were easy enough to track down.  But finally, I was getting the following message

```
[Sep 24 19:27:25.823] traffic_server NOTE: sni.yaml loading ...
[Sep 24 19:27:25.823] traffic_server ERROR: sni.yaml failed to load: 1 [1]: invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
```

It turns out the problem was that I was using the wrong key word specify disabling HTTP/2.  Used

```
h2: false
```
 Instead of 
```
http2: false
```

Seems that we should be able to give a nicer message if the key was not one that was expected.

**Comment by ywkaras** [comment] 2019-10-01 00:31
The problem is in the yaml-cpp.  There is no way to fix it without changing this library.  Which would mean we will have to have a strategy for handling new releases of this lib and merging in this or any future fixes we make.

The loader is throwing the "InvalidNode" exception.  The base exception class takes a "Mark" object which has the line and column for the error.  But the InvalidNode constructor passes null_mark to the base exception class.  The Node object contains a Mark instance.  So I thought, hey, change InvalidNode to take the Node's Mark instance.  But this causes the loader function to lock up.  So back to the drawing board.

**Comment by ywkaras** [comment] 2019-10-01 21:32
Nope I was totally wrong.  The fix is fairly simple and requires no change to the yaml-cpp file:

https://github.com/apache/trafficserver/pull/5977

**Comment by PSUdaemon** [comment] 2019-10-29 14:59
@shinrich Looks like this has been resolved?

**Comment by ywkaras** [comment] 2019-10-29 16:25
Yes, I think it is.  Sorry, I should have followed up with this.

**Comment by ezelkow1** [comment] 2019-10-31 18:51
Closing per @ywkaras

**Closed by ezelkow1** 2019-10-31 18:51 UTC
Labels: Configuration
