### ISSUE TITLE
Arena::free just set the last ArenaBlock's m_water_level

### ISSUE THREAD

**Issue by garfieldonly** [apache/trafficserver#5155] opened 2019-03-12 09:06 UTC
```
void
Arena::free(void *mem, size_t size)
{
  if (m_blocks) {
    ArenaBlock *b;

    b = m_blocks;
    while (b->next) {
      b = b->next;
    }
   // Set b the last block,if mem is at the end of b,set b's water level mem
    if (b->m_water_level == ((char *)mem + size)) {
      b->m_water_level = (char *)mem;
    }
  }
}
```

If we had three blocks in Arena,and we want to free some data in the sencond block,the free did noting.
I think if the mem is at the end of one block, we should set the block->m_water_level even if the block was'nt the last one.

**Comment by oknet** [comment] 2019-03-18 14:53
@SolidWallOfCode have been working on the `MemArena` class as a replacement for the `Arena` class.

Please keep this issue opened until the `MemArena` is merged.

**Comment by SolidWallOfCode** [comment] 2021-09-08 20:12
My `MemArena` doesn't do that either. The problem is finding the appropriate block, which requires walking all the blocks. For performance reasons, `MemArena` has the concept of a "full" block and never looks at those again. Non-stacking de-allocation
would be more trouble than it's worth for that implementation. One of the costs of using memory arenas like this is the inability
to release memory. In fact, `MemArena` doesn't have any de-allocation at all. Instead there is direct access to the unused part
of a block, which can be used without allocation, or used and then allocated. Overall I think it will work better.

[Documentation](http://docs.solidwallofcode.com/libswoc/code/MemArena.en.html).

**Comment by SolidWallOfCode** [comment] 2022-02-11 16:12
libswoc has now been added to the ATS core. IMHO it addresses this issue. Internally it will walk blocks to find memory space but will stop at the first full block. When a block becomes full due to allocation, it is moved to the front, putting it in the "full block" area. This limits the number of blocks searched to a small number.

**Closed by SolidWallOfCode** 2022-02-11 16:12 UTC
Labels: HTTP
