### ISSUE TITLE
CID 1518586: Resource leak

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#10351] opened 2023-09-01 21:02 UTC
traffic_server.cc
```
 996static bool
 997load_plugin(plugin_type_t plugin_type, const fs::path &plugin_path, std::string &error)
 998{
    	1. Switch case value plugin_type_t::GLOBAL.
 999  switch (plugin_type) {
1000  case plugin_type_t::GLOBAL: {
1001    void *handle, *initptr;
    	2. alloc_arg: plugin_dso_load allocates memory that is stored into handle. [[show details](https://scan6.scan.coverity.com/eventId=34757009-2&modelId=34757009-0&fileInstanceId=164122281&filePath=%2Fproxy%2FPlugin.cc&fileStart=103&fileEnd=121)]
    	
CID 1518586 (#1 of 1): Resource leak (RESOURCE_LEAK)
3. leaked_storage: Variable handle going out of scope leaks the storage it points to.
1002    return plugin_dso_load(plugin_path.c_str(), handle, initptr, error);
1003  }
```

**Comment by bneradt** [comment] 2023-09-25 20:27
Closing as a duplicate of #10194.

**Closed by bneradt** 2023-09-25 20:27 UTC
Labels: Coverity
