### ISSUE TITLE
ocsp stapling not supported with ats v7.1.0 and openssl 1.1.0f

### ISSUE THREAD

**Issue by esmq2092** [apache/trafficserver#2573] opened 2017-09-27 05:17 UTC
i build ats v7.1.0 againts openssl 1.1.0f, found that ocsp stapling not working.

[Sep 27 13:02:24.230] Server {0x2b0701247e00} WARNING: fail to enable ssl ocsp stapling, this openssl version does not support it
![ocsp](https://user-images.githubusercontent.com/13267484/30896934-246bd94c-a386-11e7-9a8c-c9f8bf7bc810.png)
![ocsp2](https://user-images.githubusercontent.com/13267484/30896935-246c49e0-a386-11e7-9e47-d6215f917183.png)

**Comment by calavera** [comment] 2017-09-28 00:46
OpenSSL 1.1 doesn't include the `sk_OPENSSL_STRING_pop` macro anymore. The check in OCSStapling.h needs to change to use the new api:

https://github.com/apache/trafficserver/blob/master/iocore/net/P_OCSPStapling.h#L28
https://github.com/apache/trafficserver/blob/master/iocore/net/OCSPStapling.cc#L164
https://www.openssl.org/docs/man1.1.0/crypto/OPENSSL_sk_pop.html

**Comment by randall** [comment] 2018-02-22 22:29
I filed Issue #3004, which was a duplicate of this issue. This has been fixed.

**Closed** 2018-05-10 13:19 UTC
Labels: TLS
