### ISSUE TITLE
Log Field %<cluc> always outputs "-"

### ISSUE THREAD

**Issue by ericcarlschwartz** [apache/trafficserver#1481] opened 2017-02-22 21:01 UTC
Have been doing some testing with logging the cache key field %<cluc> and every log entry seems to simply be "-". Seeing this with 7.1.

**Comment by maskit** [comment] 2017-03-01 05:46
I'm not 100% sure but it seems https://github.com/apache/trafficserver/commit/dda9df7ca7b886b5fd54d3ff6e9ed4f741948ba3 broke it. I reproduced the issue on master.

`LogAccessHttp::marshal_cache_lookup_url_canon` is not called due to a lack of `virtual`, and `LogAccess::marshal_cache_lookup_url_canon` is called instead.

I think the two special functions mentioned in the comment at  https://github.com/apache/trafficserver/commit/dda9df7ca7b886b5fd54d3ff6e9ed4f741948ba3#diff-d24873824e07e2404c39103d90347585R273 should be `marshal_entry_type ` and `marshal_process_uuid`.

`marshal_cache_lookup_url_canon ` was originally declared as a virtual function.
https://github.com/apache/trafficserver/commit/719d55b67da2fc80a4ac77860085c4e595d3326c

**Comment by zwoop** [comment] 2017-03-09 16:37
Yeh, I suck. Patch coming.

**Comment by calavera** [comment] 2017-06-08 20:44
I think this issue can be closed as resolved, right?

**Closed** 2018-11-13 06:39 UTC
Labels: Logging
