### ISSUE TITLE
CID 1518133: Resource leak

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#10194] opened 2023-08-16 17:36 UTC
```
998load_plugin(plugin_type_t plugin_type, const fs::path &plugin_path, std::string &error)
 999{
    	1. Switch case value plugin_type_t::GLOBAL.
1000  switch (plugin_type) {
1001  case plugin_type_t::GLOBAL: {
1002    void *handle, *initptr;
    	2. alloc_arg: plugin_dso_load allocates memory that is stored into handle. [[show details](https://scan6.scan.coverity.com/eventId=34735375-2&modelId=34735375-0&fileInstanceId=162996269&filePath=%2Fproxy%2FPlugin.cc&fileStart=103&fileEnd=121)]
    	
CID 1518133 (#1 of 1): Resource leak (RESOURCE_LEAK)
3. leaked_storage: Variable handle going out of scope leaks the storage it points to.
1003    return plugin_dso_load(plugin_path.c_str(), handle, initptr, error);
1004  }
```

Similar to https://github.com/apache/trafficserver/issues/10020.

**Comment by bneradt** [comment] 2023-09-25 20:28
Closing as a duplicate of #10020.

**Closed by bneradt** 2023-09-25 20:28 UTC
Labels: Coverity
