### ISSUE TITLE
Http/2 truncates large downloads

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#1646] opened 2017-04-06 23:19 UTC
The problem was with HTTP/2. The data in cache is not truncated. If requested via HTTP/1.1 the entire file is returned. If a "large enough" file is requested via HTTP/2, the stream will be closed before the last bits are delivered.

In my test, I was requesting a file 191941 bytes long.  It would download fine via http1.1, but via http2, it would stop early and only download around 180K bytes.  In verbose mode, curl would provide the following output.

```
{ [16384 bytes data]
* transfer closed with 11719 bytes remaining to read
 93  187k   93  175k    0     0   366k      0 --:--:-- --:--:-- --:--:--  368k
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
} [2 bytes data]
curl: (18) transfer closed with 11719 bytes remaining to read
```

Looking through the code, the logic to decide when to terminate the stream was flawed. It would decide that it could close the stream if

* The stream thinks it is done AND
* The amount of data available to read (before we read it) is less than or equal to the window space to send back to the client.

There is a timing flaw here if data is still flowing into the reader. We really need to check the amount of data we really read and we need to make sure the reader is empty.   I have a fix for this locally, and it seems to fix the issue.  I want to write an autest for this issue before putting up a PR.

**Comment by zwoop** [comment] 2017-04-07 06:00
Hmm, didn't @maskit fix something like this recently (like a few weeks ago)?

**Comment by maskit** [comment] 2017-04-07 17:26
The issue I fixed was caused by inactive timeout. The timer wasn't reset.

I read the code around the two condition when I fixed the issue, and it was suspicious. There should be some logic to delay termination of the stream but I won't be surprised if there is a flaw in that area.

Tests for this issue will definitely be useful!

**Comment by shinrich** [comment] 2017-04-07 20:14
Sigh, having problems reproducing in a test.  Looking for a faster machine to run the test.

**Comment by mlibbey** [comment] 2017-04-07 21:04
FWIW, there is a curl option to rate limit its throughput, which helped us in debugging a timeout issue:
curl --limit-rate 2M ...

**Comment by shinrich** [comment] 2017-04-10 13:21
Definitely fails against my working branch.  So we have a good test anyway.  Will work through to catch up my branch with the latest 7.1 and at a minimum get a regression test for this case committed.

**Comment by zwoop** [comment] 2017-04-12 17:18
@shinrich says this is likely fixed already, so closing for now.

**Closed by zwoop** 2017-04-12 17:18 UTC
Labels: HTTP/2
