### ISSUE TITLE
Increase in client aborts with H2

### ISSUE THREAD

**Issue by mlibbey** [apache/trafficserver#3536] opened 2018-04-25 23:37 UTC
We are seeing an increase of client aborts in http2 over http1 on 7.1.3:
proxy.process.http.err_client_abort_count_stat
proxy.process.http.transaction_counts.errors.aborts
- The vast majority of the aborts happen when we've sent 65535 bytes -- eg the "pscl" log. The object length varies -- eg, there isn't an obvious pattern to the object's content length.
- Most of the aborts happen for RAM cache hits.
- they get logged with cfsc="INTR" and crc="ERR_CLIENT_ABORT"

**Comment by shinrich** [comment] 2018-04-26 17:46
Hmm. We saw a spike in client aborts too bringing in the 7.1.2 changes, but our issue was due to mislogging chunked responses.  That was addressed in 7.1.3 by PR #3083 

We are tracking the differences by analyzing squid logs not looking at the stats.

**Comment by maskit** [comment] 2018-04-27 01:11
We probably need to define what client abort is. If a client close a connection abruptly (e.g. TCP Fin flag), that is obviously a client-abort from a perspective from HTTP transaction (== HttpSM). However, H2 client can GOAWAY/RST_STREAM frame with NO_ERROR/CANCEL error code. Currently they're logged as client-aborts, and they both are technically client-aborts but maybe we should log differently or log the cause to distinguish bad ones from good(harmless) ones.

Also, I think client-aborts will be increased to some extent if we turn on H2 because transactions are multiplexed. That means one abrupt connection close causes more transaction aborts than H1.

**Comment by masaori335** [comment] 2018-05-14 01:20
FWIW, TS can log Error Code in `crec` and `ctec` field by #3545.

**Comment by bryancall** [comment] 2019-05-23 20:07
Looks like this has been fixed.  Please reopen if there is still an issue.

**Closed by bryancall** 2019-05-23 20:07 UTC
Labels: HTTP/2
