### ISSUE TITLE
trafficserver should not purge expired entries with etag header

### ISSUE THREAD

**Issue by thelounge-zz** [apache/trafficserver#2801] opened 2017-11-12 21:09 UTC
As you can see in the accesslog of the backendserver after the 60 seconds are expired the cache record is obviously purged from cache while this should only happen when LRU purges and until this is the case there is no reason to not just start the 60 seconds again and continue respond from cache

the difference is that client doing a head-request can be served from cache because after revalidate the etag header it's clear that the content is still unchanged and there would be only 1 request to the origin instead 4

cache.config:
url_regex=. suffix=htm   ttl-in-cache=60s cache-responses-to-cookies=1
url_regex=. suffix=html  ttl-in-cache=60s cache-responses-to-cookies=1

127.0.0.1 - - [12/Nov/2017:22:02:31 +0100] "HEAD /test.htm HTTP/1.1" 200 - "-" "curl/7.53.1" (57%)
127.0.0.1 - - [12/Nov/2017:22:02:33 +0100] "HEAD /test.htm HTTP/1.1" 200 - "-" "curl/7.53.1" (57%)
127.0.0.1 - - [12/Nov/2017:22:02:33 +0100] "HEAD /test.htm HTTP/1.1" 200 - "-" "curl/7.53.1" (57%)
127.0.0.1 - - [12/Nov/2017:22:02:34 +0100] "HEAD /test.htm HTTP/1.1" 200 - "-" "curl/7.53.1" (57%)

[harry@srv-rhsoft:/data]$ curl --head -H "Accept-Encoding: gzip" http://example.com/test.htm
HTTP/1.1 200 OK
Date: Sun, 12 Nov 2017 20:56:12 GMT
Last-Modified: Tue, 19 Sep 2017 13:36:17 GMT
ETag: "348-5598af195ddbe-gzip"
Accept-Ranges: bytes
Content-Encoding: gzip
X-Content-Type-Options: nosniff
X-Response-Time: D=575 us
Vary: Accept-Encoding
Cache-Control: private
Content-Length: 501
Content-Type: text/html
Age: 53
Connection: keep-alive

[harry@srv-rhsoft:/data]$ curl --head -H "Accept-Encoding: gzip" http://example.com/test.htm
HTTP/1.1 200 OK
Date: Sun, 12 Nov 2017 20:57:58 GMT
Last-Modified: Tue, 19 Sep 2017 13:36:17 GMT
ETag: "348-5598af195ddbe-gzip"
Accept-Ranges: bytes
Content-Encoding: gzip
X-Content-Type-Options: nosniff
X-Response-Time: D=555 us
Vary: Accept-Encoding
Cache-Control: private
Content-Length: 501
Content-Type: text/html
Age: 0

**Comment by thelounge-zz** [comment] 2017-11-12 21:12
and the orign could just respond with a "304 Not Modified" instead of the whole body and in the case above even skip compression at all which would reduce load and network traffic

**Comment by mlibbey** [comment] 2018-11-13 11:35
I'm not able to reproduce this using ATS 7.1.4. I first tried having the origin do the right Cache-Control (eg, with max-age, public), fetched the object once with a GET through ATS, and waited for it to go stale. I then used a HEAD to ATS, and successfully saw ATS send the origin a INM HEAD request -- the origin returned a 304 and ATS successfully refreshed thee object in cache. Then I set cache.config to override the origin's CC: private. Again, fetched the object into cache with a GET; waited for it to go stale, and fetched again using a HEAD. ATS again made an INM HEAD request to origin; the origin responded with a 304 Not Modified and ATS refreshed the object in cache.

I don't actually see a GET to ATS in the report; nor proof that ATS had it in cache (eg, a HEAD will not fill the cache -- it needs an initial GET). If the object was never in cache, that would explain the report. So... could you fetch the object with a GET; then fetch it again with -H "Cache-Control:only-if-cached" (or if you have the X-Debug plugin running, with -H "X-Debug: X-Cache" to ensure its in cache); then once its stale, fetch via the HEAD?

**Comment by thelounge-zz** [comment] 2018-11-13 11:40
why does ATS not do the initial GET request to fill the cache?
the behavior means with HEAD requests you can completly take the proxy out of the game

**Comment by mlibbey** [comment] 2018-11-13 21:38
The background fetch plugin creates a new "internal" request to go fetch the full object when it sees a Range Request that could be served from cache in the future. Your best bet is to change the client to use a 0 byte Range request, and have background fetch get the object cached. You might be able to modify the plugin to look for HEADs. Or imitate it using the lua plugin. Or have the lua plugin change the inbound head request into a 0 byte range GET. Of course, any of this could result in wasted and higher origin loads than the HEAD proxies. In your example, the origin told you not to cache the object. The object may be uncacheable for other reasons (too big, etc).

**Comment by zwoop** [comment] 2019-02-19 21:15
i think @SolidWallOfCode might either have a new plugin, or extensions to background_fetch, which allows filling cache objects when it sees a HEAD object. Going to close this for now, with the assumption that he will open source this  :).

**Closed by zwoop** 2019-02-19 21:15 UTC
