### ISSUE TITLE
ATS only uses one cpu for https

### ISSUE THREAD

**Issue by thelounge-zz** [apache/trafficserver#3502] opened 2018-04-19 15:59 UTC
why in the world is ATS using all 4 cores with non-https and only 1 core with https?
you can see that pretty simple in "htop" when you have nearly 400% CPU versus not even 100%

in both cases "ab -c 150 -n 500000 -k" (keep-alive) for the same tiny image
the difference is terrible and httpd scales way better while ATS is lithtning fast with non-tls traffic

Server Port:            8080
Concurrency Level:      150
Time taken for tests:   11.909 seconds
Complete requests:      500000
Failed requests:        0
Keep-Alive requests:    500000
Total transferred:      501610980 bytes
HTML transferred:       321500000 bytes
Requests per second:    41986.10 [#/sec] (mean)
Time per request:       3.573 [ms] (mean)
Time per request:       0.024 [ms] (mean, across all concurrent requests)
Transfer rate:          41134.16 [Kbytes/sec] received

Server Port:            8443
SSL/TLS Protocol:       TLSv1.2,ECDHE-ECDSA-AES128-GCM-SHA256,256,128
Concurrency Level:      150
Time taken for tests:   109.969 seconds
Complete requests:      390054
Failed requests:        0
Keep-Alive requests:    390054
Total transferred:      391602759 bytes
HTML transferred:       250804722 bytes
Requests per second:    3546.94 [#/sec] (mean)
Time per request:       42.290 [ms] (mean)
Time per request:       0.282 [ms] (mean, across all concurrent requests)
Transfer rate:          3477.56 [Kbytes/sec] received

**Comment by mlibbey** [comment] 2018-04-23 21:31
Think this is a setup or configuration issue. I just ran the same for a small object over http/https:

http:
Concurrency Level:      150
Time taken for tests:   17.619 seconds
Complete requests:      500000
Failed requests:        0
Write errors:           0
Keep-Alive requests:    500000
Total transferred:      629011322 bytes
HTML transferred:       310505589 bytes
Requests per second:    28377.84 [#/sec] (mean)
Time per request:       5.286 [ms] (mean)
Time per request:       0.035 [ms] (mean, across all concurrent requests)
Transfer rate:          34863.24 [Kbytes/sec] received

https:
Concurrency Level:      150
Time taken for tests:   15.014 seconds
Complete requests:      500000
Failed requests:        0
Write errors:           0
Keep-Alive requests:    500000
Total transferred:      628516341 bytes
HTML transferred:       310508073 bytes
Requests per second:    33301.56 [#/sec] (mean)
Time per request:       4.504 [ms] (mean)
Time per request:       0.030 [ms] (mean, across all concurrent requests)
Transfer rate:          40880.03 [Kbytes/sec] received

I saw all cores increase in htop for both http and https.

**Comment by thelounge-zz** [comment] 2018-04-23 21:34
the good question is which config setting would lead to such a weird behavior

**Comment by thelounge-zz** [comment] 2018-04-23 22:09
remove any thread related config option don't make a difference

Requests per second:    3572.92 [#/sec] (mean)
Time per request:       41.982 [ms] (mean)
Time per request:       0.280 [ms] (mean, across all concurrent requests)
Transfer rate:          3503.82 [Kbytes/sec] received

CONFIG proxy.config.exec_thread.autoconfig INT 0
CONFIG proxy.config.exec_thread.limit INT 4
CONFIG proxy.config.exec_thread.affinity INT 1
CONFIG proxy.config.accept_threads INT 0
CONFIG proxy.config.cache.threads_per_disk INT 8
CONFIG proxy.config.task_threads INT 2
___________________

cat records.config | grep -v "CONFIG proxy.config.exec_thread.autoconfig" | grep -v "CONFIG proxy.config.exec_thread.limit" | grep -v "CONFIG proxy.config.exec_thread.affinity" | grep -v "CONFIG proxy.config.accept_threads" | grep -v "CONFIG proxy.config.cache.threads_per_disk" | grep -v "CONFIG proxy.config.task_threads"

**Comment by thelounge-zz** [comment] 2018-04-23 22:10
[root@buildserver:~]$ cat /etc/trafficserver/records.config 
##############################################################################
# System Variables                                                           #
##############################################################################
CONFIG proxy.config.proxy_name STRING proxy.thelounge.net
CONFIG proxy.config.config_dir STRING /etc/trafficserver
CONFIG proxy.config.proxy_binary_opts STRING -M
CONFIG proxy.config.alarm_email STRING ats
CONFIG proxy.config.syslog_facility STRING LOG_DAEMON
CONFIG proxy.config.output.logfile STRING traffic.out
CONFIG proxy.config.snapshot_dir STRING snapshots

##############################################################################
# Main threads configuration (worker threads). Also see configurations for   #
# SSL threads, disk I/O threads and task threads in their respective areas   #
##############################################################################

##############################################################################
# Local Manager                                                              #
##############################################################################
CONFIG proxy.config.admin.admin_user STRING admin
CONFIG proxy.config.admin.number_config_bak INT 0
CONFIG proxy.config.admin.user_id STRING ats

##############################################################################
# Process Manager                                                            #
##############################################################################
CONFIG proxy.config.process_manager.mgmt_port INT 8084

##############################################################################
# HTTP Engine                                                                #
##############################################################################
CONFIG proxy.config.http.server_ports STRING 8080 8443:ssl
CONFIG proxy.config.http.connect_ports STRING 80
CONFIG proxy.config.http.insert_request_via_str INT 0
CONFIG proxy.config.http.insert_response_via_str INT 0
CONFIG proxy.config.http.response_server_enabled INT 0
CONFIG proxy.config.http.insert_age_in_response INT 1
CONFIG proxy.config.http.no_dns_just_forward_to_parent INT 0
CONFIG proxy.config.http.uncacheable_requests_bypass_parent INT 0
CONFIG proxy.config.http.keep_alive_enabled_in INT 1
CONFIG proxy.config.http.keep_alive_enabled_out INT 1
CONFIG proxy.config.http.origin_min_keep_alive_connections INT 0
CONFIG proxy.config.http.chunking_enabled INT 1
CONFIG proxy.config.http.send_http11_requests INT 1
CONFIG proxy.config.http.referer_filter INT 0
CONFIG proxy.config.http.strict_uri_parsing INT 0

##############################################################################
# parent proxy configuration                                                 #
##############################################################################
CONFIG proxy.config.http.parent_proxy_routing_enable INT 0

##############################################################################
# HTTP connection timeouts (secs)                                            #
# out: proxy -> origin server connection                                     #
# in : ua -> proxy connection                                                #
##############################################################################
CONFIG proxy.config.http.keep_alive_no_activity_timeout_in INT 5
CONFIG proxy.config.http.keep_alive_no_activity_timeout_out INT 1
CONFIG proxy.config.http.transaction_no_activity_timeout_in INT 30
CONFIG proxy.config.http.transaction_no_activity_timeout_out INT 300
CONFIG proxy.config.http.transaction_active_timeout_in INT 900
CONFIG proxy.config.http.transaction_active_timeout_out INT 0
CONFIG proxy.config.http.accept_no_activity_timeout INT 30
CONFIG proxy.config.http.background_fill_active_timeout INT 0
CONFIG proxy.config.http.background_fill_completed_threshold FLOAT 0.0

##############################################################################
# origin server connect attempts                                             #
##############################################################################
CONFIG proxy.config.http.connect_attempts_max_retries INT 10
CONFIG proxy.config.http.connect_attempts_max_retries_dead_server INT 10
CONFIG proxy.config.http.connect_attempts_rr_retries INT 10
CONFIG proxy.config.http.connect_attempts_timeout INT 30
CONFIG proxy.config.http.post_connect_attempts_timeout INT 1800
CONFIG proxy.config.http.down_server.cache_time INT 1
CONFIG proxy.config.http.down_server.abort_threshold INT 30

##############################################################################
# congestion control                                                         #
##############################################################################
CONFIG proxy.config.http.congestion_control.enabled INT 0

##############################################################################
# negative response caching                                                  #
##############################################################################
CONFIG proxy.config.http.negative_caching_enabled INT 0
CONFIG proxy.config.http.negative_caching_lifetime INT 1

##############################################################################
# proxy users variables                                                      #
##############################################################################
CONFIG proxy.config.http.anonymize_remove_from INT 0
CONFIG proxy.config.http.anonymize_remove_referer INT 0
CONFIG proxy.config.http.anonymize_remove_user_agent INT 0
CONFIG proxy.config.http.anonymize_remove_cookie INT 0
CONFIG proxy.config.http.anonymize_remove_client_ip INT 0
CONFIG proxy.config.http.anonymize_other_header_list STRING NULL
CONFIG proxy.config.http.insert_squid_x_forwarded_for INT 1

##############################################################################
# security                                                                   #
##############################################################################
CONFIG proxy.config.http.push_method_enabled INT 0

##############################################################################
# cache control                                                              #
##############################################################################
CONFIG proxy.config.http.normalize_ae INT 1
CONFIG proxy.config.http.cache.http INT 1
CONFIG proxy.config.http.cache.cache_responses_to_cookies INT 4
CONFIG proxy.config.http.cache.cache_urls_that_look_dynamic INT 1
CONFIG proxy.config.http.cache.ims_on_client_no_cache INT 1
CONFIG proxy.config.http.cache.ignore_client_cc_max_age INT 0
CONFIG proxy.config.http.cache.ignore_client_no_cache INT 0
CONFIG proxy.config.http.cache.ignore_accept_mismatch INT 2
CONFIG proxy.config.http.cache.ignore_accept_language_mismatch INT 2
CONFIG proxy.config.http.cache.ignore_accept_encoding_mismatch INT 2
CONFIG proxy.config.http.cache.ignore_accept_charset_mismatch INT 2
CONFIG proxy.config.http.cache.ignore_server_no_cache INT 0
CONFIG proxy.config.http.cache.ignore_authentication INT 0
CONFIG proxy.config.http.cache.enable_default_vary_headers INT 0
CONFIG proxy.config.http.cache.when_to_revalidate INT 0
CONFIG proxy.config.http.cache.required_headers INT 2
CONFIG proxy.config.http.cache.max_stale_age INT 1800
CONFIG proxy.config.http.cache.range.lookup INT 0

##############################################################################
# heuristic expiration                                                       #
##############################################################################
CONFIG proxy.config.http.cache.heuristic_min_lifetime INT 60
CONFIG proxy.config.http.cache.heuristic_max_lifetime INT 60
CONFIG proxy.config.http.cache.heuristic_lm_factor FLOAT 0.100000
CONFIG proxy.config.http.cache.fuzz.time INT 60
CONFIG proxy.config.http.cache.fuzz.probability FLOAT 0.005000

##############################################################################
# dynamic content & content negotiation                                      #
##############################################################################
CONFIG proxy.config.http.cache.vary_default_text STRING Accept-Encoding
CONFIG proxy.config.http.cache.vary_default_images STRING NULL
CONFIG proxy.config.http.cache.vary_default_other STRING NULL

##############################################################################
# The HTTP stats are expensive, turn off you dont need them                  #
##############################################################################
CONFIG proxy.config.http.enable_http_stats INT 0

##############################################################################
# Customizable User Response Pages                                           #
##############################################################################
CONFIG proxy.config.body_factory.enable_customizations INT 1
CONFIG proxy.config.body_factory.enable_logging INT 0
CONFIG proxy.config.body_factory.response_suppression_mode INT 0

##############################################################################
# Net Subsystem                                                              #
##############################################################################
CONFIG proxy.config.net.connections_throttle INT 30000
CONFIG proxy.config.net.defer_accept INT 1
CONFIG proxy.config.net.poll_timeout INT 25

##############################################################################
# Cluster Subsystem                                                          #
##############################################################################
LOCAL proxy.local.cluster.type INT 3

##############################################################################
# Cache                                                                      #
##############################################################################
CONFIG proxy.config.cache.ram_cache.size INT 128M
CONFIG proxy.config.cache.ram_cache_cutoff INT 512K
CONFIG proxy.config.cache.ram_cache.algorithm INT 1
CONFIG proxy.config.cache.ram_cache.use_seen_filter INT 0
CONFIG proxy.config.cache.ram_cache.compress INT 0
CONFIG proxy.config.cache.limits.http.max_alts INT 10
CONFIG proxy.config.cache.max_doc_size INT 0
CONFIG proxy.config.cache.enable_read_while_writer INT 1
CONFIG proxy.config.allocator.hugepages INT 0
CONFIG proxy.config.cache.permit.pinning INT 0

##############################################################################
# DNS                                                                        #
##############################################################################
CONFIG proxy.config.dns.search_default_domains INT 1
CONFIG proxy.config.dns.splitDNS.enabled INT 0
CONFIG proxy.config.dns.max_dns_in_flight INT 2048
CONFIG proxy.config.dns.round_robin_nameservers INT 0
CONFIG proxy.config.dns.nameservers STRING 127.0.0.1
CONFIG proxy.config.dns.resolv_conf STRING NULL
CONFIG proxy.config.dns.validate_query_name INT 0

##############################################################################
# HostDB                                                                     #
##############################################################################
CONFIG proxy.config.hostdb.ttl_mode INT 1
CONFIG proxy.config.hostdb.timeout INT 60
CONFIG proxy.config.hostdb.strict_round_robin INT 0
CONFIG proxy.config.hostdb.host_file.path STRING /etc/hosts.dnsmasq
CONFIG proxy.config.hostdb.host_file.interval INT 60
CONFIG proxy.config.hostdb.ip_resolve STRING ipv4;none

##############################################################################
# Logging Config                                                             #
#                                                                            #
# 0: no logging at all                                                       #
# 1: log errors only                                                         #
# 2: log transactions only                                                   #
# 3: full logging (errors + transactions)                                    #
##############################################################################
LOCAL proxy.local.log.collation_mode INT 0
CONFIG proxy.config.log.logging_enabled INT 1
CONFIG proxy.config.log.max_secs_per_buffer INT 5
CONFIG proxy.config.log.max_space_mb_for_logs INT 25000
CONFIG proxy.config.log.max_space_mb_for_orphan_logs INT 25
CONFIG proxy.config.log.max_space_mb_headroom INT 1000
CONFIG proxy.config.log.hostname STRING localhost
CONFIG proxy.config.log.logfile_dir STRING /var/log/trafficserver
CONFIG proxy.config.log.logfile_perm STRING rw-rw----
CONFIG proxy.config.log.collation_host STRING NULL
CONFIG proxy.config.log.collation_port INT 8085
CONFIG proxy.config.log.collation_secret STRING foobar
CONFIG proxy.config.log.collation_host_tagged INT 0
CONFIG proxy.config.log.collation_retry_sec INT 5
CONFIG proxy.config.log.rolling_enabled INT 1
CONFIG proxy.config.log.rolling_interval_sec INT 86400
CONFIG proxy.config.log.rolling_offset_hr INT 0
CONFIG proxy.config.log.rolling_size_mb INT 10
CONFIG proxy.config.log.auto_delete_rolled_files INT 1
CONFIG proxy.config.log.sampling_frequency INT 1

##############################################################################
# Reverse Proxy                                                              #
##############################################################################
CONFIG proxy.config.reverse_proxy.enabled INT 1
CONFIG proxy.config.header.parse.no_host_url_redirect STRING NULL

##############################################################################
# URL Remap Rules                                                            #
##############################################################################
CONFIG proxy.config.url_remap.remap_required INT 1
CONFIG proxy.config.url_remap.pristine_host_hdr INT 1

##############################################################################
# Socket send/recv buffer sizes 0 == dont call setsockopt()                  #
# out: proxy -> os connection                                                #
# in : ua -> proxy connection                                                #
##############################################################################
CONFIG proxy.config.net.sock_send_buffer_size_in INT 0
CONFIG proxy.config.net.sock_recv_buffer_size_in INT 0
CONFIG proxy.config.net.sock_option_flag_in INT 0
CONFIG proxy.config.net.sock_send_buffer_size_out INT 0
CONFIG proxy.config.net.sock_recv_buffer_size_out INT 0

##############################################################################
# User Overridden Configurations Below                                       #
##############################################################################
CONFIG proxy.config.core_limit INT -1
CONFIG proxy.config.disable_configuration_modification INT 1

##############################################################################
# Debugging                                                                  #
##############################################################################
CONFIG proxy.config.diags.debug.enabled INT 0
CONFIG proxy.config.diags.debug.tags STRING http.*|dns.*
CONFIG proxy.config.dump_mem_info_frequency INT 0

##############################################################################
# Log any request that takes more then x number of milliseconds, needs       #
# to be > 0 to be enabled                                                    #
##############################################################################
CONFIG proxy.config.http.slow.log.threshold INT 0

##############################################################################
# Thread pool for "misc" tasks, plugins etc. 2 is a good minimum             #
##############################################################################
CONFIG proxy.config.cluster.cluster_configuration STRING cluster.config
CONFIG proxy.config.body_factory.template_sets_dir STRING /etc/trafficserver/body_factory

##############################################################################
# SSL/TLS                                                                    #
##############################################################################
CONFIG proxy.config.ssl.TLSv1 INT 1
CONFIG proxy.config.ssl.TLSv1_1 INT 1
CONFIG proxy.config.ssl.TLSv1_2 INT 1
CONFIG proxy.config.ssl.client.TLSv1 INT 1
CONFIG proxy.config.ssl.client.TLSv1_1 INT 1
CONFIG proxy.config.ssl.client.TLSv1_2 INT 1
CONFIG proxy.config.ssl.client.certification_level INT 0
CONFIG proxy.config.ssl.server.multicert.filename STRING ssl_multicert.config
CONFIG proxy.config.ssl.server.cert.path STRING /etc/trafficserver/ssl/
CONFIG proxy.config.ssl.server.private_key.path STRING /etc/trafficserver/ssl/
CONFIG proxy.config.ssl.CA.cert.path STRING /etc/trafficserver/ssl/
CONFIG proxy.config.ssl.server.cipher_suite STRING ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-CAMELLIA128-SHA:DHE-RSA-CAMELLIA256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA:AES256-SHA:CAMELLIA128-SHA:CAMELLIA256-SHA:!LOW:!MEDIUM
CONFIG proxy.config.ssl.server.honor_cipher_order INT 1
CONFIG proxy.config.ssl.server.dhparams_file STRING /etc/trafficserver/ssl/dhparams.pem
CONFIG proxy.config.ssl.ocsp.enabled INT 0

**Comment by thelounge-zz** [comment] 2018-07-03 15:34
always the latest version, i don't write upstream bugreports for anything else

trafficserver-7.1.3-5.0.fc27.20180514.rh.sandybridge.x86_64
openssl-1.1.0h-3.fc27.x86_64

**Comment by thelounge-zz** [comment] 2018-07-03 15:35
httpd is built with the same options and has no issues like that - also remember taht the benchmark is even with keep-alive so there should be not much overhead on ssl-layer and on aes-ni machines the enrcyption itself is nearly free

**Comment by SolidWallOfCode** [comment] 2018-07-03 17:20
I have to agree with Miles, though - Susan has done tests specifically for TLS throughput and the performace was not much different from HTTP, and that was on 7.1.x. The problem is AFAIK no one else is seeing this behavior, either in testing or production use. Over half our inbound traffic is TLS and we'd definitely notice if only one core was being used. What I might try is enabling the slow log and see what is taking time for the very long TLS transactions. Since the average is about 40 seconds, you could set the slow log to something like 100000 ms and check those.

**Comment by shinrich** [comment] 2018-07-03 18:05
I'd try setting proxy.config.accept_threads to 1.  May or may not help with your work distribution but dedicated accept threads tend to be more efficient.  If that is the problem, then we have a flaw in the non-dedicated accept thread case.

**Comment by thelounge-zz** [comment] 2018-07-03 20:05
@SolidWallOfCode "Since the average is about 40 seconds" - WHAT?
42.290 [ms]

this are 42.29 ms and not 40 seconds
if the avergae is 40 seconds i throw ATS away and install httpd with mod_proxy given that the backend system can generate 30000 dynamic cms requests per second on it's own with the only downside of keep-alive given mod_php runs with mpm_forker and that's the reason for ATS at all: buffer spikes for static files for 60 seconds

**Comment by thelounge-zz** [comment] 2018-07-03 20:15
@shinrich how should "proxy.config.accept_threads" help?

AGAIN: in both cases "ab -c 150 -n 500000 -k" (keep-alive) for the same tiny image
-k == keep-alive, there are no connections to accept all the time
the point is that with keep-alive you have little handshake overhead and shouldn't see much difference between http and https at all which is true for httpd but not ATS

handshakes are not part of the game, but anyways with accept_threads

8080: Requests per second:    34800 [#/sec] (mean)
8443: Requests per second:    3607 [#/sec] (mean)

httpd:
80: Requests per second:    11993
443: Requests per second:    10181

**Comment by SolidWallOfCode** [comment] 2018-07-03 20:50
I wonder if it's a session sharing issue - given the timing, it looks like ATS is doing TLS negotiation on every upstream connection.

**Comment by thelounge-zz** [comment] 2018-07-03 21:02
but again: keep-alive -> there is only one tls-handshake and one time TLS negotiation for a connection

**Comment by SolidWallOfCode** [comment] 2018-07-05 15:51
That would be why it would be interesting to get some slow log data for the longest transactions and see where the time is actually going.

**Comment by thelounge-zz** [comment] 2018-07-05 16:00
where and how do you configure "slow log" when the avg response time is 40ms?
i also posted the complete config file (why ever gitgub thought it needs to format it)

**Comment by SolidWallOfCode** [comment] 2018-07-09 02:17
[Slow log configuration](https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html#proxy-config-http-slow-log-threshold).

Yes, I looked through the configuration, nothing seemed obviously wrong.

**Comment by bryancall** [comment] 2019-05-23 20:01
Looks like this has been fixed.  Please reopen if there is still an issue.

**Closed by bryancall** 2019-05-23 20:01 UTC

**Comment by thelounge-zz** [comment] 2019-05-23 20:12
how does it look like it's been fixed?
