### ISSUE TITLE
mysql_remap + logging - "cquuc" cannot return unmapped url

### ISSUE THREAD

**Issue by chuyenim** [apache/trafficserver#4697] opened 2018-12-11 06:53 UTC
When I use mysql_remap for remapping, "cquuc" return origin url instead of unmapped url.

**Comment by mlibbey** [comment] 2018-12-13 05:41
Think this a duplicate of #4684

**Comment by mlibbey** [comment] 2018-12-13 05:44
Oh. Sorry -- are you sure you mean cquuc? We use that, and it logs the inbound/alias url. But, we don't use the mysql_remap plugin.

**Comment by chuyenim** [comment] 2018-12-14 03:59
@mlibbey:  Yes I mean cquuc - client_req_unmapped_url_canonical

**Comment by chuyenim** [comment] 2018-12-14 04:03
I found this:
```
int
LogAccess::marshal_client_req_unmapped_url_canon(char *buf)
{
  int len = INK_MIN_ALIGN;

  validate_unmapped_url();
  if (m_client_req_unmapped_url_canon_str == INVALID_STR) {
    // If the unmapped URL isn't populated, we'll fall back to the original
    // client URL. This helps for example server intercepts to continue to
    // log the requests, even when there is no remap rule for it.
    len = marshal_client_req_url_canon(buf);
  } else {
    len = round_strlen(m_client_req_unmapped_url_canon_len + 1); // +1 for eos
    if (buf) {
      marshal_mem(buf, m_client_req_unmapped_url_canon_str, m_client_req_unmapped_url_canon_len, len);
    }
  }

  return len;
}
```

It said: "**If the unmapped URL isn't populated, we'll fall back to the original client URL. This helps for example server intercepts to continue to log the requests, even when there is no remap rule for it.**"
But I think unmapped URLs is more helpful than original client URLs. And I want to catch them.

**Comment by maskit** [comment] 2021-06-28 23:46
mysql_remap plugin is deprecated. I think we can close this issue.
https://github.com/apache/trafficserver/blame/c3827da3170bc1b5784eb9f6a7d5796981b56838/doc/admin-guide/plugins/mysql_remap.en.rst#L23-L27

**Comment by shinrich** [comment] 2021-06-29 19:13
I took a quick look at the old mysql_remap plugin.  It was a global plugin that triggered on the read request hook (before the remap phase), and it would call functions that would have updated the client request storage before the remap phase (TSUrlHostSet, TSUrlSchemeSet, TSUrlPortSet).

We should have a read-only version of the original client request information.  I will go ahead and file a new issue to track that.

**Closed** 2021-06-29 19:14 UTC
Labels: Logging, Plugins
